use_frameworks!

target 'YTTCache_Example' do
  pod 'YTTCache', :path => '../'
  pod 'SQLite.swift', '~> 0.11.5'

  target 'YTTCache_Tests' do
    inherit! :search_paths
    pod 'YTTCache', :path => '../'  
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
