use_frameworks!

target 'YTTCache_Example' do
  pod 'YTTCache'
  pod 'SQLite.swift', '~> 0.11.5'

  target 'YTTCache_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
